### PR TITLE
Mark expired cfp as closed

### PR DESCRIPTION
**Pull request by blablatdinov**
ref: #64

### CODE REVIEW

**Comment by blablatdinov** [comment]
@yegor256 Try rerun workflow manually, pls. Tests fail because code coverege down. However, locally I take 100% test coverage

**Comment by blablatdinov** [comment]
@yegor256 sorry, `tests.sh` run update `fixtures` dir and mark expired dates as closed, so python tests not run expired date case. Take a look

**Comment by yegor256** [comment]
@blablatdinov do I understand correctly that the conferences with expired "cfp" won't be rendered in the table at all?

**Comment by blablatdinov** [comment]
@yegor256 No, trey are rendered as "closed", check [test case](https://github.com/yegor256/awesome-cfp/pull/67/files#diff-77b34a8560d623a2228d82e14ca0b980fbaf1c1cce895f230ea7b8e9c4dd1271)

**Comment by yegor256** [comment]
@blablatdinov thanks!

**Pull request merged**
