### PR TITLE
13 validate links

### PR DESCRIPTION
**Pull request by blablatdinov**
ref: #13

### CODE REVIEW

**Comment by blablatdinov** [comment]
@yegor256 We still need the file `test.sh`?

**Comment by blablatdinov** [comment]
@yegor256 What about redirection (301, 302, ... statuses)? It's okay?

**Comment by yegor256** [comment]
@blablatdinov yes, they are fine. Let's treat them as "OK"

**Comment by blablatdinov** [comment]
@yegor256 take a look

**Comment by yegor256** [comment]
@blablatdinov thanks!

**Pull request merged**
