### PR TITLE
#10 add github action for check expired dates

### PR DESCRIPTION
**Pull request by uchitsa**

### CODE REVIEW

**Comment by uchitsa** [comment]
@yegor256 please fix last check with solution https://github.com/actions/checkout/issues/417#issuecomment-1797881377.
It works in my fork https://github.com/uchitsa/awesome-cfp/actions/runs/9911110040.

**Comment by uchitsa** [comment]
@yegor256 hello, please check PR

**Comment by yegor256** [comment]
@uchitsa what's the point of changing dates inside the `README.md` file, if another script a few moments later will set them back using the information in the `cfp.yml` file?

**Comment by uchitsa** [comment]
@yegor256 agree, fix it. Add cron schedule for check-dates action.

**Comment by yegor256** [comment]
@uchitsa I don't see the changes. In this branch, you are still making changes to README and creating a new pull request.

**Pull request closed without merging**
